//! A prompt that uses git-style merge conflict markers to represent the editable region.
//!
//! Example prompt:
//!
//! <|file_sep|>path/to/target_file.py
//! <|fim_prefix|>
//! code before editable region
//! <|fim_suffix|>
//! code after editable region
//! <|fim_middle|>
//! <<<<<<< CURRENT
//! code that
//! needs to<|user_cursor|>
//! be rewritten
//! =======
//!
//! Expected output (should be generated by the model):
//!
//! updated
//! code with
//! changes applied
//! >>>>>>> UPDATED

use super::*;

pub const START_MARKER: &str = "<<<<<<< CURRENT\n";
pub const SEPARATOR: &str = "=======\n";
pub const END_MARKER: &str = ">>>>>>> UPDATED\n";

pub fn special_tokens() -> &'static [&'static str] {
    &[
        "<|fim_prefix|>",
        "<|fim_suffix|>",
        "<|fim_middle|>",
        "<|file_sep|>",
        START_MARKER,
        SEPARATOR,
        END_MARKER,
        CURSOR_MARKER,
    ]
}

pub fn write_cursor_excerpt_section(
    prompt: &mut String,
    path: &Path,
    context: &str,
    editable_range: &Range<usize>,
    cursor_offset: usize,
) {
    let path_str = path.to_string_lossy();
    write!(prompt, "<|file_sep|>{}\n", path_str).ok();

    prompt.push_str("<|fim_prefix|>");
    prompt.push_str(&context[..editable_range.start]);

    prompt.push_str("<|fim_suffix|>");
    prompt.push_str(&context[editable_range.end..]);
    if !prompt.ends_with('\n') {
        prompt.push('\n');
    }

    prompt.push_str("<|fim_middle|>");
    prompt.push_str(START_MARKER);
    prompt.push_str(&context[editable_range.start..cursor_offset]);
    prompt.push_str(CURSOR_MARKER);
    prompt.push_str(&context[cursor_offset..editable_range.end]);
    if !prompt.ends_with('\n') {
        prompt.push('\n');
    }
    prompt.push_str(SEPARATOR);
}
