#!/usr/bin/env bash

set -euxo pipefail

if [[ $# -gt 0 ]]; then
  echo "
  Usage: ${0##*/}
  Builds and installs mav onto your system into ~/.local, making it available as ~/.local/bin/mav.

  Before running this you should ensure you have all the build dependencies installed with `./script/linux`.
  "
  exit 1
fi
export MAV_CHANNEL=$(<crates/mav/RELEASE_CHANNEL)
export MAV_UPDATE_EXPLANATION="You need to fetch and rebuild mav in $(pwd)"
script/bundle-linux

arch="$(uname -m)"
commit=$(git rev-parse HEAD | cut -c 1-7)
archive="mav-linux-${arch}.tar.gz"
export MAV_BUNDLE_PATH="${CARGO_TARGET_DIR:-target}/release/${archive}"
script/install.sh
