use super::*;

pub(super) struct FinalSurfaceLayouts {
    pub(super) cursors: Vec<(DisplayPoint, Hsla)>,
    pub(super) visible_cursors: Vec<CursorLayout>,
    pub(super) navigation_overlay_paint_commands: Vec<NavigationOverlayPaintCommand>,
    pub(super) scrollbars_layout: Option<EditorScrollbars>,
    pub(super) mouse_context_menu: Option<AnyElement>,
    pub(super) test_indicators: Vec<AnyElement>,
    pub(super) bookmarks: Vec<AnyElement>,
    pub(super) breakpoints: Vec<AnyElement>,
    pub(super) diff_review_button: Option<AnyElement>,
    pub(super) wrap_guides: SmallVec<[(Pixels, bool); 2]>,
    pub(super) minimap: Option<MinimapLayout>,
    pub(super) tab_invisible: ShapedLine,
    pub(super) space_invisible: ShapedLine,
    pub(super) mode: EditorMode,
    pub(super) diff_hunk_controls: Vec<AnyElement>,
    pub(super) position_map: Rc<PositionMap>,
    pub(super) crease_toggles: Vec<Option<AnyElement>>,
    pub(super) expand_toggles: Vec<Option<(AnyElement, gpui::Point<Pixels>)>>,
}

impl EditorElement {
    #[allow(clippy::too_many_arguments)]
    pub(super) fn layout_final_surface(
        &self,
        bounds_size: Size<Pixels>,
        visible_row_range: Range<DisplayRow>,
        snapshot: &EditorSnapshot,
        selections: &[(PlayerColor, Vec<SelectionLayout>)],
        row_block_types: &HashMap<DisplayRow, bool>,
        line_layouts: Vec<LineWithInvisibles>,
        text_hitbox: &Hitbox,
        gutter_hitbox: &Hitbox,
        content_origin: gpui::Point<Pixels>,
        scroll_position: gpui::Point<ScrollOffset>,
        scroll_pixel_position: gpui::Point<ScrollPixelOffset>,
        scroll_max: gpui::Point<ScrollPixelOffset>,
        line_height: Pixels,
        em_width: Pixels,
        em_advance: Pixels,
        em_layout_width: Pixels,
        autoscroll_containing_element: bool,
        redacted_ranges: &[Range<DisplayPoint>],
        scrollbar_layout_information: &ScrollbarLayoutInformation,
        content_offset: gpui::Point<Pixels>,
        right_margin: Pixels,
        editor_width: Pixels,
        hitbox: &Hitbox,
        gutter_dimensions: GutterDimensions,
        gutter: &Gutter,
        row_infos: &[RowInfo],
        run_indicator_rows: &HashSet<DisplayRow>,
        breakpoint_rows: &mut HashMap<
            DisplayRow,
            (Anchor, Breakpoint, Option<BreakpointSessionState>),
        >,
        newest_selection_head: Option<DisplayPoint>,
        style: &EditorStyle,
        current_selection_head: Option<DisplayRow>,
        is_read_only: bool,
        sticky_headers: &Option<header::StickyHeaders>,
        has_sticky_buffer_header: bool,
        blocks: &[BlockLayout],
        display_hunks: &[(DisplayDiffHunk, Option<Hitbox>)],
        highlighted_rows: &BTreeMap<DisplayRow, LineHighlight>,
        vertical_scrollbar_width: Pixels,
        minimap_width: Pixels,
        font_size: Pixels,
        inline_blame_layout: Option<&InlineBlameLayout>,
        crease_toggles: &mut Vec<Option<AnyElement>>,
        expand_toggles: &mut Vec<Option<(AnyElement, gpui::Point<Pixels>)>>,
        window: &mut Window,
        cx: &mut App,
    ) -> FinalSurfaceLayouts {
        let layout_data::CursorSurfaceLayouts {
            cursors,
            visible_cursors,
            navigation_overlay_paint_commands,
            scrollbars_layout,
        } = self.layout_cursor_surface(
            snapshot,
            selections,
            row_block_types,
            visible_row_range.clone(),
            &line_layouts,
            text_hitbox,
            content_origin,
            scroll_position,
            scroll_pixel_position,
            line_height,
            em_width,
            em_advance,
            autoscroll_containing_element,
            redacted_ranges,
            scrollbar_layout_information,
            content_offset,
            right_margin,
            editor_width,
            window,
            cx,
        );

        let gutter_settings = EditorSettings::get_global(cx).gutter;

        let layout_data::MenuPopoverLayouts { mouse_context_menu } = self
            .layout_menus_and_popovers(
                snapshot,
                hitbox,
                text_hitbox,
                content_origin,
                right_margin,
                gutter_dimensions,
                scroll_pixel_position,
                newest_selection_head,
                visible_row_range.clone(),
                &line_layouts,
                line_height,
                em_width,
                style,
                window,
                cx,
            );

        let layout_data::GutterIndicatorLayouts {
            test_indicators,
            bookmarks,
            breakpoints,
            diff_review_button,
        } = self.layout_gutter_indicators(
            gutter,
            visible_row_range.clone(),
            row_infos,
            snapshot,
            run_indicator_rows,
            breakpoint_rows,
            gutter_settings,
            gutter_dimensions,
            line_height,
            em_width,
            window,
            cx,
        );

        window.with_element_namespace("crease_toggles", |window| {
            self.prepaint_crease_toggles(
                crease_toggles,
                line_height,
                &gutter_dimensions,
                gutter_settings,
                scroll_position,
                visible_row_range.start,
                gutter_hitbox,
                window,
                cx,
            )
        });

        window.with_element_namespace("expand_toggles", |window| {
            self.prepaint_expand_toggles(expand_toggles, window, cx)
        });

        let layout_data::FinalVisualLayouts {
            wrap_guides,
            minimap,
            tab_invisible,
            space_invisible,
            mode,
        } = self.layout_final_visuals(
            snapshot,
            em_advance,
            scroll_position,
            content_origin,
            scrollbars_layout.as_ref(),
            vertical_scrollbar_width,
            hitbox,
            minimap_width,
            scrollbar_layout_information,
            font_size,
            window,
            cx,
        );

        let layout_data::DiffHunkControlLayouts {
            diff_hunk_controls,
            diff_hunk_control_bounds,
        } = self.layout_diff_hunk_control_phase(
            is_read_only,
            sticky_headers,
            has_sticky_buffer_header,
            blocks,
            scroll_position,
            visible_row_range.clone(),
            row_infos,
            text_hitbox,
            current_selection_head,
            line_height,
            right_margin,
            scroll_pixel_position,
            display_hunks,
            highlighted_rows,
            window,
            cx,
        );

        let layout_data::PositionMapLayout { position_map } = self.layout_position_map(
            bounds_size,
            visible_row_range,
            scroll_position,
            scroll_pixel_position,
            scroll_max,
            line_layouts,
            line_height,
            em_advance,
            em_layout_width,
            snapshot.clone(),
            text_hitbox.size.width,
            gutter_hitbox,
            text_hitbox,
            inline_blame_layout,
            display_hunks,
            diff_hunk_control_bounds,
            scrollbars_layout.as_ref(),
            right_margin,
            cx,
        );

        FinalSurfaceLayouts {
            cursors,
            visible_cursors,
            navigation_overlay_paint_commands,
            scrollbars_layout,
            mouse_context_menu,
            test_indicators,
            bookmarks,
            breakpoints,
            diff_review_button,
            wrap_guides,
            minimap,
            tab_invisible,
            space_invisible,
            mode,
            diff_hunk_controls,
            position_map,
            crease_toggles: mem::take(crease_toggles),
            expand_toggles: mem::take(expand_toggles),
        }
    }
}
